# Generated by Django 5.2.4 on 2025-07-06 10:40

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0002_blogpost_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='slug_post',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, populate_from='title', unique=True),
        ),
    ]
